{{- range $profile := .Values.profiles }}
{{- if and $profile.credentials $profile.credentials.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "staemme.profileName" (dict "Release" $.Release "profile" $profile) }}-credentials
  labels:
    {{- include "staemme.labels" $ | nindent 4 }}
    staemme/profile: {{ $profile.name }}
type: Opaque
data:
  username: {{ $profile.credentials.username | b64enc | quote }}
  password: {{ $profile.credentials.password | default "" | b64enc | quote }}
{{- end }}
{{- end }}
