# Defensive village building template

[buildings]
main = 20
farm = 30
storage = 30
wood = 30
stone = 30
iron = 30
hide = 10
barracks = 25
stable = 10
garage = 2
smith = 20
market = 15
place = 1
wall = 20
watchtower = 5
statue = 1

[priority]
order = [
    "main",
    "farm",
    "storage",
    "wall",
    "wood",
    "stone",
    "iron",
    "barracks",
    "hide",
    "smith",
    "watchtower",
    "stable",
    "market",
    "garage",
    "place",
    "statue",
]
